name: Auto-Merge PR from Action (No Checks)

on:
  pull_request:
    types: [opened]

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Merge PR
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.mergeable == true && github.event.pull_request.draft == false }}
      run: |
        git merge "${{ github.event.pull_request.head.sha }}" --no-edit
        git push
